[project]
name = "pv-recommend"
version = "0.1.0"
description = "Python 推荐模块"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.1",
    "numpy>=2.2.5",
    "pymysql>=1.1.1",
    "scikit-learn>=1.6.1",
]
